FROM carlosati/ubuntu_ati

#Pasos para usar imagen :

#    Crear un Dockerfile con el siguiente contenido:

#FROM carlosati/ubuntu_ati

#    Construir la imagen, ejecutando el siguiente comando en la ubicacion del Dockerfile:

#docker build ./

#    Ejecutar un contenedor:

#docker run -tid -p '8090:80' --privileged carlosati/ubuntu_ati "/sbin/init"

#    Verificar contenedor en ejecucion con el comando docker ps, abrir sesion interactiva:

#docker exec -it <container_id> /bin/bash

#Acceder al servidor apache desde el navegador

#Abrir el navegador del host principal y acceder a:

#    http://localhost:8090/ATI:
#    http://localhost:8090/info.php

#Usuario/Clave para acceder a directorio http://localhost:8090/ATI: carlosati/carloscasti
